export const VITE_DEFAULT_TOILET_MAILS = 'VITE_DEFAULT_TOILET_MAILS';
export const VITE_DEFAULT_ELECTRICITY_MAILS = 'VITE_DEFAULT_ELECTRICITY_MAILS';

export const VITE_HIDDEN_PAGE_KEYS = 'VITE_HIDDEN_PAGE_KEYS';
